Django_web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# urlpatterns = [                                # 双层路由
#     path("admin/", admin.site.urls),            # 看到"admin/"这个请求，就将请求转向admin.site.urls路由
#     path("user/", include("DjangoWebApps.user.urls", namespace='user')),        # 用户模块
#     # path("goods/", include("DjangoWebApps.dw_goods.urls", namespace='goods')),      # 商品模块
#     path("cart/", include("DjangoWebApps.cart.urls", namespace='cart')),        # 购物车模块
#     path("order/", include("DjangoWebApps.order.urls", namespace='order')),      # 订单模块
#     path("", include("DjangoWebApps.goods.urls", namespace='goods')),      # 商品模块
#
# ]
# Django_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # 用户模块 - 修改这里
    path("user/", include(("apps.user.urls", "user"), namespace="user")),
    # 其他模块保持不变
    path("cart/", include(("apps.cart.urls", "cart"), namespace="cart")),
    # path("goods/", include(("DjangoWebApps.goods.urls", "goods"), namespace="goods")),
    path("order/", include(("apps.order.urls", "order"), namespace="order")),
    path("goods/", include(("apps.goods.urls", "goods"), namespace="goods")),
    # 富文本编辑器
    path("tinymce/", include(("tinymce.urls", "tinymce"))),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DongDongQiang/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),    # ，二级路由。指引到admin.site.urls文件的url
    path('user/', include(('ddq_user.urls', 'user'))),  # 用户模块
    path('cart/', include(('ddq_cart.urls', 'cart'))),  # 购物车模块
    path('order/', include(('ddq_order.urls', 'order'))),  # 订单模块
    path('', include(('ddq_goods.urls', 'goods'))),  # 商品模块
    path('tinymce/', include('tinymce.urls')),
    path(r'search', include('haystack.urls')),  # 全文检索框架
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/urls.py
# # cart/urls.py
# from django.urls import path
# from . import views
#
# app_name = 'cart'
#
# urlpatterns = [
#     path('', views.cart_detail, name='cart_detail'),
#     path('add/<int:product_id>/', views.cart_add, name='cart_add'),
#     path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
# ]
from django.urls import path


urlpatterns = [

]

apps/ddq_cart/urls.py
# coding:utf-8
from django.urls import path,re_path
from .views import *

urlpatterns = [
    path('add', CartAddView.as_view(), name='add'),  # 购物车记录添加
    path('', CartInfoView.as_view(), name='show'),  # 购物车页面显示
    path('update', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    path('delete', CartDeleteView.as_view(), name='delete'),  # 购物车记录删除
]

'''
在 Django 2.0 之后，推荐使用path()和re_path()代替旧的url()函数，并且不再需要手动添加^（开始）和$（结束）正则表达式符号
'''

apps/ddq_goods/urls.py
# coding:utf-8
from django.urls import path,re_path
from .views import IndexView, DetailView, ListView

urlpatterns = [
    path('index', IndexView.as_view(), name='index'), # 首页
    re_path(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'), # 详情页
    # 未完成
    re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
    path('', IndexView.as_view(), name='index'),
]

apps/ddq_order/urls.py
# coding:utf-8
from django.urls import path, re_path
from apps.ddq_order.views import OrderPlaceView, OrderCommitView, CommentView, PayOrderView

urlpatterns = [
    path('place', OrderPlaceView.as_view(), name='place'),  # 提交订单页面显示
    path('commit', OrderCommitView.as_view(), name='commit'),  # 提交创建
    re_path(r'comment/(?P<order_id>.+)/$', CommentView.as_view(), name='comment'),  # 订单评论
    path('pay/<int:order_id>/', PayOrderView.as_view(), name='pay_order'),
]

apps/ddq_user/urls.py
# coding:utf-8
# apps/ddq_user/urls.py
from django.urls import path, re_path
# from django.contrib.auth.decorators import login_required
from .views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserHistoryView, UserOrderView, UserAddressView
from .views import UserBalanceView
'''
导入django模块中的login_required方法
验证用户是否是登录状态，也就是获取session的值
如果用户是登录状态，那么则可以访问需要登录成功后所访问的页面
如果用户未登录，直接访问需要登录后才能看到的页面
则login_required方法默认跳转到 http://127.0.0.1:8000/accounts/login/?next=/user/ 页面
'''

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),     # 注册页面
    # re_path(r"register_handle$", views.register_handle, name="register_handle"),  # 注册数据处理,考虑是否需要用正则表达式
    re_path(r"^active/(?P<token>.*)$", ActiveView.as_view(), name="active"),  # 账户激活
    re_path(r"^login$", LoginView.as_view(), name="login"),  # 登录
    re_path(r'^logout$', LogoutView.as_view(), name='logout'), # 退出登陆

    # 封装前 为不美观不统一而封装
    # url(r'^$', login_required(UserInfoView.as_view()), name='user'), # 用户中心-信息页
    # url(r'^order$', login_required(UserOrderView.as_view()), name='order'), # 用户中心-订单页
    # url(r'^address$', login_required(AddressView.as_view()), name='address'), # 用户中心-地址页

    re_path(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    re_path(r"^order/(?P<page>\d+)$", UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    re_path(r'^address$', UserAddressView.as_view(), name='address'),  # 用户中心-地址页
    path("history", UserHistoryView.as_view(), name="history"), # 用户中心-浏览记录
    path('balance', UserBalanceView.as_view(), name='balance'), # 余额充值
]

apps/cart/models.py
# # cart/cart.py
# from django.conf import settings
# from DjangoWebApps.goods.models import Product
#
# class Cart:
#     def __init__(self, request):
#         self.session = request.session
#         cart = self.session.get(settings.CART_SESSION_ID)
#         if not cart:
#             cart = self.session[settings.CART_SESSION_ID] = {}
#         self.cart = cart
#
#     def add(self, product, quantity=1, override_quantity=False):
#         product_id = str(product.id)
#         if product_id not in self.cart:
#             self.cart[product_id] = {'quantity': 0, 'price': str(product.price)}
#
#         if override_quantity:
#             self.cart[product_id]['quantity'] = quantity
#         else:
#             self.cart[product_id]['quantity'] += quantity
#
#         self.save()
#
#     def save(self):
#         self.session.modified = True
#
#     def remove(self, product):
#         product_id = str(product.id)
#         if product_id in self.cart:
#             del self.cart[product_id]
#             self.save()
#
#     def __iter__(self):
#         product_ids = self.cart.keys()
#         products = Product.objects.filter(id__in=product_ids)
#
#         cart = self.cart.copy()
#         for product in products:
#             cart[str(product.id)]['product'] = product
#
#         for item in cart.values():
#             item['total_price'] = item['price'] * item['quantity']
#             yield item
#
#     def __len__(self):
#         return sum(item['quantity'] for item in self.cart.values())
#
#     def get_total_price(self):
#         return sum(float(item['price']) * item['quantity'] for item in self.cart.values())
#
#     def clear(self):
#         del self.session[settings.CART_SESSION_ID]
#         self.save()

apps/cart/views.py
# # cart/views.py
# from django.shortcuts import render, redirect, get_object_or_404
# from DjangoWebApps.goods.models import Product
# from .cart import Cart
# from .forms import CartAddProductForm
#
# def cart_add(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     form = CartAddProductForm(request.POST)
#
#     if form.is_valid():
#         cd = form.cleaned_data
#         cart.add(
#             product=product,
#             quantity=cd['quantity'],
#             override_quantity=cd['override']
#         )
#
#     return redirect('cart:cart_detail')
#
# def cart_remove(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     cart.remove(product)
#     return redirect('cart:cart_detail')
#
# def cart_detail(request):
#     cart = Cart(request)
#     for item in cart:
#         item['update_quantity_form'] = CartAddProductForm(initial={
#             'quantity': item['quantity'],
#             'override': True
#         })
#     return render(request, 'cart/cart_detail.html', {'cart': cart})

templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}   {# 导入静态文件 #}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">

	{# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到咚咚锵!</div> {# fl指明左对齐，并不是类名 #}
			<div class="fr">   {# float right 的缩写，用于将该元素设置为右浮动  #}
{#                Django框架默认会给前端模板文件传递request.user对象#}
{#                如果用户是登录状态访问页面会返回User类的对象user#}
{#                如果未登录则返回AnonymousUser实力对象，当给前端模板文件返回的是user对象（已登录）#}
{#                则这个实力对象去调is_authenticated方法则会返回True，#}
{#                （未登录）AnonymousUser实力对象去调用is_authenticated方法则会返回False #}
{#                在base.html模板文件中根据user对象进行判断#}
{#                                                                                  #}
{#                如果没有使用重复模板的继承复用，#}
{#                则需要在有class=‘header_con’模块的模板文件中一一进行判断#}
{#                在此体现出重复内容模板继承的重要性#}
				{% if user.is_authenticated %}
				<div class="login_btn fl">  {# 右对齐的header容器中左对齐,以最后的对齐类为其左右对齐类 #}
					欢迎您：<em style="color: #f89752;">{{ user.username }}</em>
					<span>|</span>   {# 行内以"|"间隔 #}
					<a href="{% url 'user:logout' %} ">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">我的订单</a>
					<span>|</span>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索块 #}
{% block search_bar %}
<div class="top-bar">
    <div class="logo-container">
        <a href="{% url 'goods:index' %}" class="site-logo">
            <img src="{% static 'images/logo.png' %}" alt="咚咚锵">
        </a>
    </div>

    <div class="search-box">
        <form method="get" action="/search">
            <input type="text" name="q" class="search-input" name="q" placeholder="搜索商品、品牌、类别...">
            <button type="submit" class="search-button">搜索</button>
        </form>
        <div class="hot-words">
            <span class="highlight">热门搜索：</span>
            <a href="/search?q=上海大学" class="highlight">上海大学</a>
            <a href="/search?q=手机" class="highlight">手机</a>
            <a href="/search?q=水果">水果</a>
            <a href="/search?q=葡萄">葡萄</a>
        </div>
    </div>

    <div class="cart-box">
        <a href="{% url 'cart:show' %}" class="cart-link">🛒 我的购物车</a>
        <span class="cart-count" id="show_count">{{ cart_count }}</span>
    </div>
</div>
{% endblock search_bar %}
</body>
{# 网页主体内容块 #}
{% block body %}
{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 上海咚咚锵信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    沪ICP备*******8号</p>
	</div>
{# 网页底部html引入元素块 #}
{% block bottom %}
{% endblock bottom %}

{# 网页底部引入文件块 #}
{% block bottomfiles %}
{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{% block body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for type in types %}
{#                <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>#}
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="{% url 'goods:index' %}">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">大牌奥莱</a></li>
            <li class="interval">|</li>
            <li><a href="">美妆馆</a></li>
            <li class="interval">|</li>
            <li><a href="">超市</a></li>
            <li class="interval">|</li>
            <li><a href="">生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">咚咚锵国际</a></li>
            <li class="interval">|</li>
            <li><a href="">拍卖</a></li>
            <li class="interval">|</li>
        </ul>
    </div>
</div>
{# 详情页, 列表页主体内容块 #}
{% block main_content %}
{% endblock main_content %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}咚咚锵-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price}}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

templates/login.html
{#<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">#}
{#<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">#}
{#{% load static %}   {# 导入静态文件 #}
{#<head>#}
{#	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">#}
{#	<title>咚咚锵-登录</title>#}
{#	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">#}
{#	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">#}
{#</head>#}
{#<body>#}
{% extends 'base.html' %}
{% load static %}   {# 导入静态文件 #}
{% block title %}咚咚锵-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo.png' %}" width="193" height="90"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">汝之所需 · 使命必达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post"> <!--action不写默认表示与登录地址一致，跟用户注册一样，使用同一地址显示并处理登录-->
                        {% csrf_token %} {# CSRF保护，防止跨站请求伪造攻击 #}
                        <!-- 临时添加，用于调试 -->
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名" autocomplete="off">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    <span style="color: red">{{ error_msg }}</span>  {# 数据不合法的情况下，提示错误信息 #}
{#</body>#}
{% endblock body %}
{#</html>#}

templates/register.html
{% extends 'base.html' %}
{% load static %}   {# 导入静态文件 #}
{% block title %}咚咚锵-注册{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}

{% block header_con %}{% endblock header_con %}

{% block search_bar %}{% endblock search_bar %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo.png'%}" width="193" height="90"></a>
			<div class="reg_slogan">咚咚锵  ·  又快！又好！</div>
{#			<div class="reg_banner"></div>#}
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register' %}">  <!-- 定义一个 HTML 表单，用于用户输入数据并提交到服务器。注册页面数据是以POST请求方式向服务器发送 -->
                    <!-- 注册优化处理，让显示注册页面和注册数据处理为同一个url地址（/user/register） ，因为显示注册页面为get请求，而注册数据处理为post请求，可以根据请求方式不同来使用同一个url地址-->
				<ul>   <!-- 定义一个无序列表，用于组织表单中的各个输入项 -->
                    <!-- 表单其他字段和内容 -->
					<li>   <!-- 定义一个列表项，用于包含表单中的输入字段和标签 -->
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”咚咚锵用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
                    {% csrf_token %} {# 在django中发送POST请求表单数据，防止跨站攻击需在form标签下加上{% csrf_token %} #}
                    <span style="color: red">{{ error_msg }}</span>  {# 数据不合法的情况下，提示错误信息 #}
				</form>
			</div>

		</div>

	</div>
{% endblock body %}
{#</html>#}

templates/user_center_balance.html
{% extends 'user_center_info.html' %}
{% load static %}
{% block right_content %}
    <h2>我的余额</h2>
    <div class="user-balance">
        <h3>账户余额</h3>
        <p><strong>当前余额：</strong>¥ {{ balance.amount|default:"0.00" }}</p>
        <form action="{% url 'user:balance' %}" method="post" class="recharge-form">
            {% csrf_token %}
            <input type="number" name="amount" step="0.01" min="0.01" placeholder="请输入充值金额">
            <button type="submit">立即充值</button>
        </form>
    </div>
{% endblock right_content %}

templates/user_center_history.html
{#{% extends 'base_no_cart.html' %}#}
{% load static %}   {# 导入静态文件 #}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>最近浏览</title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <style>

  </style>
</head>
<body>
  <h3 class="common_title2">最近浏览</h3>
  <div class="has_view_list">
    <ul class="goods_type_list clearfix">
      {% for goods in goods_li %}
      <li>
        <a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
        <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
        <div class="operate">
          <span class="prize">￥{{ goods.price }}</span>
          <span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
          <a href="#" class="add_goods" title="加入购物车"></a>
        </div>
      </li>
      {% empty %}
        无历史浏览记录
      {% endfor %}
    </ul>
  </div>
</body>
</html>

templates/user_center_info.html
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}咚咚锵-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
<div class="user-center-container">
  <div class="user-sidebar">
    <h3>用户中心</h3>
    <ul>
      <li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
      <li><a href="{% url 'user:balance' %}" {% if page == 'balance' %}class="active"{% endif %}>· 我的余额</a></li>
      <li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
      <li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
      <li><a href="{% url 'user:history' %}" {% if page == 'history' %}class="active"{% endif %}>· 最近浏览</a></li>
      <li><a href="{% url 'cart:show' %}" {% if page == 'show' %}class="active"{% endif %}>· 我的收藏</a></li>
    </ul>
  </div>
  <div class="user-main">
    {% block right_content %}
    <h2>欢迎回来，{{ user.username }}！</h2>
    <div class="user-info">
      <p><strong>用户名：</strong>{{ user.username }}</p>
      <p><strong>邮箱：</strong>{{ user.email }}</p>
      <p><strong>注册时间：</strong>{{ user.date_joined }}</p>
      <p><strong>上次登录：</strong>{{ user.last_login }}</p>
    </div>
    {% endblock right_content %}
  </div>
</div>
{% endblock body %}

templates/user_center_site.html
{% extends 'user_center_info.html' %}
{% load static %}
{% block title %}咚咚锵-用户中心-收货地址{% endblock title %}
{% block page_title %}用户中心 - 收货地址{% endblock page_title %}
{% block right_content %}
<div class="right_content clearfix">
    <h3 class="common_title2">收货地址</h3>
    <div class="site_con">
        {% for address in addresses %}
        <dl>
            <dt>地址{{ forloop.counter }}：</dt>
            <dd>
                <input type="radio" name="default_address" value="{{ address.id }}" {% if address.is_default %}checked{% endif %}>
                {{ address.addr }} ({{ address.receiver }} 收) {{ address.phone }}
            </dd>
        </dl>
        {% endfor %}
    </div>
    <h3 class="common_title2">编辑地址</h3>
    <div class="site_con">
        <form method="post">
            {% csrf_token %}
            <div class="form_group">
                <label>收件人：</label>
                <input type="text" name="receiver" {% if default_address %}value="{{ default_address.receiver }}"{% endif %}>
            </div>
            <div class="form_group form_group2">
                <label>详细地址：</label>
                <textarea class="site_area" name="addr">{% if default_address %}{{ default_address.addr }}{% endif %}</textarea>
            </div>
            <div class="form_group">
                <label>手机：</label>
                <input type="text" name="phone" {% if default_address %}value="{{ default_address.phone }}"{% endif %}>
            </div>
            <input type="submit" name="" value="提交" class="info_submit">
            <ul>
                <span style="color: red">{{ errmsg }}</span>  <!-- 数据不合法的情况下，提示错误信息 -->
            </ul>
        </form>
    </div>
</div>

{% endblock right_content %}